server:
  port: 81

spring:
  datasource:
    password: root1234
    url: jdbc:postgresql://localhost:5432/codingbat
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true